image: python:3
lint:
 stage: test
 script:
 - pip install yapf
 - yapf --style google -i --recursive .
 only:
 - pushes

unittest:
 stage: test
 script:
 - pip install -r requirements.txt
 - pytest .
 only:
 - pushes

 prod:
 image: google/cloud-sdk:alpine
 stage: deploy
 environment: Production
 only:
 - main
 script:
 - echo $SERVICE_ACCOUNT > /tmp/$CI_PIPELINE_ID.json
 - gcloud auth activate-service-account --key-file /tmp/$CI_PIPELINE_ID.json
 - --quiet --project $PROJECT_ID
 - gcloud app deploy